import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="dark:bg-black bg-[#F2F2F0]  font-sf-pro main-bg relative">
        {children}
      </body>
    </html>
  );
}
