import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning className="h-full antialiased">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              document.documentElement.classList.toggle(
                "dark",
                localStorage.getItem("theme") === "dark"
              );
            `,
          }}
        />
      </head>
      <body className="dark:bg-black bg-[#F2F2F0]  font-sf-pro main-bg relative">
        {children}
      </body>
    </html>
  );
}
